device_id: "emulator-5554"
app_package: "com.google.android.youtube"
app_activity: "com.google.android.apps.youtube.app.watchwhile.WatchWhileActivity"
plugins:
  - screenshot_plugin
test_cases:
  - network_test
metadata:
  version: "1.0"